spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    ru.bk.j3000.normarchivedata: info

server:
  port: 5050