spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
logging:
  level:
    ru.bk.j3000.normarchivedata: info