spring:
  datasource:
    url: ${DB_URL_TEST}
    password: ${DB_PASSWORD_TEST}
    username: ${DB_USER_TEST}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
logging:
  level:
    ru.bk.j3000.normarchivedata: debug

server:
  port: 5050