spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    ru.bk.j3000.normarchivedata: debug
    org.springframework.security: info

server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: keystore/norm.p12
    key-alias: ${KEYSTORE_ALIAS}
    key-store-password: ${KEYSTORE_PASSWORD}
    enabled: true